[book]
authors = ["Jared Harper"]
language = "en"
multilingual = false
src = "src"
title = "OpenBSD Notes"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/lucky/openbsd-notes"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/lucky/openbsd-notes/edit/main/{path}"
site-url = "/openbsd-notes/"
cname = "hrpr.us"
